# 
# AppScope JSON schema CI workflow
#
# This is the GitHub Workflow to generate JSON schema markdown and push
# to staging site at https://staging.appscope.dev/.
#
name: JSON Schema Markdown website update

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'docker/docs/layout.js'
      - 'docs/schemas/**'
jobs:
  build-commit-json-schema:
    name: Build JSON schema reference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Schema
        run: make docs-generate

      - name: "Github Action: Auto commit schema-reference.md"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update JSON Schema Markdown file
          file_pattern: "./website/src/pages/docs/schema-reference.md"
