# 
# AppScope Website CI Workflow
#
# This is the GitHub workflow for AppScope's production website at
# https://appscope.dev/ and the staging site at
# https://staging.appscope.dev/.
#
# We publish `web*` tags to the production site. Other pushes to the
# master branch get published to the staging site.
#
name: Deploy Website
on:
  push:
    branches:
      - master
    tags:
      - 'web*'
    paths:
      - 'website/**'
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Website Deploy"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: ./website/deploy.sh
